# Generated by Django 5.1.6 on 2026-10-08 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor_label", models.CharField(blank=True, max_length=160)),
                ("action", models.CharField(db_index=True, max_length=64)),
                ("object_type", models.CharField(blank=True, max_length=48)),
                (
                    "object_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("summary", models.CharField(max_length=255)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("ip", models.CharField(blank=True, max_length=45)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "common_audit_event",
                "ordering": ("-at",),
            },
        ),
    ]
