# Generated by Django 5.1.6 on 2026-10-07 13:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=48, unique=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[("insurance", "Insurance"), ("lending", "Loans")],
                        max_length=12,
                    ),
                ),
                ("regulator", models.CharField(max_length=150)),
                ("licence_number", models.CharField(blank=True, max_length=64)),
                ("connector", models.CharField(max_length=48)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "marketplace_provider",
            },
        ),
        migrations.CreateModel(
            name="FinancialProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[("insurance", "Insurance"), ("lending", "Loans")],
                        max_length=12,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("min_minor", models.BigIntegerField(blank=True, null=True)),
                ("max_minor", models.BigIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="marketplace.financialprovider",
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_product",
            },
        ),
        migrations.CreateModel(
            name="ProductApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=16, unique=True)),
                ("amount_minor", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted to partner"),
                            ("pending", "Under review by partner"),
                            ("approved", "Approved by partner"),
                            ("declined", "Declined by partner"),
                            ("failed", "Could not be sent"),
                        ],
                        max_length=10,
                    ),
                ),
                ("partner_ref", models.CharField(blank=True, max_length=64)),
                ("message", models.CharField(blank=True, max_length=255)),
                ("consent_given_at", models.DateTimeField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="marketplace.financialproduct",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_application",
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="marketplace_user_id_fe657a_idx",
                    )
                ],
            },
        ),
    ]
