# Generated by Django 5.1.6 on 2026-10-07 14:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("premium", "Premium paid from wallet"),
                            ("disbursement", "Loan disbursed to wallet"),
                        ],
                        max_length=12,
                    ),
                ),
                ("amount_minor", models.BigIntegerField()),
                (
                    "partner_ref",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="marketplace.productapplication",
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_product_txn",
            },
        ),
    ]
