# Generated by Django 5.1.6 on 2026-10-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_producttransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialproduct",
            name="category",
            field=models.CharField(
                choices=[
                    ("insurance", "Insurance"),
                    ("lending", "Loans"),
                    ("savings", "Savings"),
                    ("investment", "Investments"),
                    ("pension", "Pensions"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="financialprovider",
            name="category",
            field=models.CharField(
                choices=[
                    ("insurance", "Insurance"),
                    ("lending", "Loans"),
                    ("savings", "Savings"),
                    ("investment", "Investments"),
                    ("pension", "Pensions"),
                ],
                max_length=12,
            ),
        ),
    ]
