# Generated by Django 5.1.6 on 2026-10-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_alter_financialproduct_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("requested", "Requested, waiting for the provider"),
                    ("rejected", "Rejected by the provider"),
                ],
                default="completed",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="producttransaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("premium", "Premium paid from wallet"),
                    ("disbursement", "Loan disbursed to wallet"),
                    ("contribution", "Paid in from wallet"),
                    ("withdrawal", "Paid out to wallet"),
                ],
                max_length=12,
            ),
        ),
    ]
