# Generated by Django 5.1.6 on 2026-10-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="app",
            field=models.CharField(
                choices=[
                    ("customer", "Customer app"),
                    ("agent", "Agent app"),
                    ("merchant", "Merchant app"),
                ],
                default="customer",
                max_length=8,
            ),
        ),
    ]
