# Generated by Django 5.1.6 on 2026-10-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_device_app"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="target_app",
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
