# Generated by Django 5.1.6 on 2026-10-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_target_app"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="sms_fallback",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="sms_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
