# Generated by Django 5.1.6 on 2026-10-08 13:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0005_cashoutrequest_fee_minor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("fee", "Fee charged by SokoPay"),
                            ("commission", "Commission paid to agents"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "product",
                    models.CharField(
                        choices=[
                            ("bill", "Bill payment (customer pays on top)"),
                            ("airtime", "Airtime (customer pays on top)"),
                            ("data", "Data bundle (customer pays on top)"),
                            ("cash_out", "Agent cash-out (customer pays on top)"),
                            ("cash_in", "Agent cash-in"),
                            (
                                "bulk_momo",
                                "Bulk payout to mobile money (merchant pays)",
                            ),
                            ("bulk_bank", "Bulk payout to bank (merchant pays)"),
                        ],
                        max_length=12,
                    ),
                ),
                ("flat_minor", models.PositiveIntegerField(default=0)),
                ("percent_bp", models.PositiveIntegerField(default=0)),
                ("min_minor", models.PositiveIntegerField(default=0)),
                ("max_minor", models.PositiveIntegerField(default=0)),
                ("effective_from", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(max_length=255)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pricing_rule",
            },
        ),
        migrations.CreateModel(
            name="AgentCommission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product", models.CharField(max_length=12)),
                ("amount_minor", models.BigIntegerField()),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commissions",
                        to="agents.agent",
                    ),
                ),
                (
                    "txn",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission",
                        to="agents.agenttxn",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pricing.pricerule",
                    ),
                ),
            ],
            options={
                "db_table": "pricing_agent_commission",
            },
        ),
        migrations.AddIndex(
            model_name="pricerule",
            index=models.Index(
                fields=["kind", "product", "status", "effective_from"],
                name="pricing_rul_kind_09720c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentcommission",
            index=models.Index(
                fields=["agent", "created_at"], name="pricing_age_agent_i_93cd6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentcommission",
            index=models.Index(
                fields=["paid_at"], name="pricing_age_paid_at_3adf2d_idx"
            ),
        ),
    ]
