# Generated by Django 5.1.6 on 2026-10-07 18:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("merchants", "0002_merchant_short_code_paymentrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkPayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("note", models.CharField(blank=True, max_length=120)),
                ("source_filename", models.CharField(max_length=200)),
                ("file_sha256", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft — review rows"),
                            ("awaiting_approval", "Awaiting approval"),
                            ("processing", "Paying recipients"),
                            ("completed", "Completed"),
                            (
                                "completed_with_failures",
                                "Completed — some failed (refunded)",
                            ),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("exclude_invalid", models.BooleanField(default=False)),
                ("total_count", models.IntegerField(default=0)),
                ("valid_count", models.IntegerField(default=0)),
                ("invalid_count", models.IntegerField(default=0)),
                ("total_amount_minor", models.BigIntegerField(default=0)),
                ("total_fee_minor", models.BigIntegerField(default=0)),
                ("reserved_minor", models.BigIntegerField(default=0)),
                ("paid_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("self_approved", models.BooleanField(default=False)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.CharField(blank=True, max_length=255)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bulk_payouts_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bulk_payouts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bulk_payouts",
                        to="merchants.merchant",
                    ),
                ),
            ],
            options={
                "db_table": "bulk_payout",
            },
        ),
        migrations.CreateModel(
            name="BulkPayoutItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_number", models.IntegerField()),
                ("recipient_name", models.CharField(max_length=120)),
                (
                    "destination_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sokopay", "SokoPay wallet"),
                            ("momo", "Mobile money"),
                            ("bank", "Bank account"),
                            ("wallet", "Other fintech wallet"),
                        ],
                        max_length=8,
                    ),
                ),
                ("institution", models.CharField(blank=True, max_length=32)),
                ("account", models.CharField(blank=True, max_length=34)),
                ("amount_minor", models.BigIntegerField(default=0)),
                ("fee_minor", models.BigIntegerField(default=0)),
                ("narrative", models.CharField(blank=True, max_length=140)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invalid", "Invalid — will not be paid"),
                            ("valid", "Ready"),
                            ("skipped", "Skipped (invalid row excluded)"),
                            ("processing", "Sent — awaiting confirmation"),
                            ("paid", "Paid"),
                            ("failed", "Failed — refunded to merchant"),
                        ],
                        max_length=12,
                    ),
                ),
                ("error", models.CharField(blank=True, max_length=255)),
                ("connector", models.CharField(blank=True, max_length=32)),
                (
                    "provider_ref",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="bulk.bulkpayout",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bulk_payout_item",
                "ordering": ("row_number",),
            },
        ),
        migrations.AddIndex(
            model_name="bulkpayout",
            index=models.Index(
                fields=["merchant", "status", "created_at"],
                name="bulk_payout_merchan_11b7d5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bulkpayoutitem",
            index=models.Index(
                fields=["batch", "status"], name="bulk_payout_batch_i_3c1a7f_idx"
            ),
        ),
    ]
