# Generated by Django 5.2.18 on 2026-10-10 09:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiBriefing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("for_date", models.DateField(db_index=True)),
                ("text", models.TextField()),
                ("model", models.CharField(blank=True, max_length=64)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "insights_ai_briefing",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AiInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("chat", "Question"), ("briefing", "Daily briefing")],
                        max_length=10,
                    ),
                ),
                ("question", models.TextField(blank=True)),
                ("redactions", models.JSONField(blank=True, default=list)),
                ("tools_used", models.JSONField(blank=True, default=list)),
                ("model", models.CharField(blank=True, max_length=64)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(default="ok", max_length=10)),
                ("error", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "insights_ai_interaction",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="insights_ai_created_4bfb4d_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="insights_ai_user_id_dbae23_idx",
                    ),
                ],
            },
        ),
    ]
