# Generated by Django 5.1.6 on 2026-10-07 07:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(max_length=150)),
                ("location", models.CharField(blank=True, max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agents_agent",
            },
        ),
        migrations.CreateModel(
            name="AgentTxn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("topup", "Float top-up"),
                            ("cash_in", "Cash in"),
                            ("cash_out", "Cash out"),
                        ],
                        max_length=10,
                    ),
                ),
                ("customer_phone", models.CharField(blank=True, max_length=16)),
                ("amount_minor", models.BigIntegerField()),
                ("currency", models.CharField(default="GHS", max_length=3)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="agents.agent",
                    ),
                ),
            ],
            options={
                "db_table": "agents_txn",
                "indexes": [
                    models.Index(
                        fields=["agent", "created_at"],
                        name="agents_txn_agent_i_59b6c6_idx",
                    )
                ],
            },
        ),
    ]
