# Generated by Django 5.1.6 on 2026-10-08 08:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashOutRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_minor", models.BigIntegerField()),
                ("currency", models.CharField(default="GHS", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for the customer"),
                            ("approved", "Approved — cash paid out"),
                            ("declined", "Declined by the customer"),
                            ("expired", "Expired"),
                            ("failed", "Couldn't be completed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_out_requests",
                        to="agents.agent",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_out_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "txn",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_out_request",
                        to="agents.agenttxn",
                    ),
                ),
            ],
            options={
                "db_table": "agents_cash_out_request",
                "indexes": [
                    models.Index(
                        fields=["customer", "status", "expires_at"],
                        name="agents_cash_custome_88ff33_idx",
                    )
                ],
            },
        ),
    ]
