# Generated by Django 5.1.6 on 2026-10-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_floattopup"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashoutrequest",
            name="fee_minor",
            field=models.BigIntegerField(default=0),
        ),
    ]
