# Generated by Django 5.1.6 on 2026-10-07 00:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LedgerAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=128, unique=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("income", "Income"),
                            ("expense", "Expense"),
                            ("equity", "Equity"),
                        ],
                        max_length=16,
                    ),
                ),
                ("owner_type", models.CharField(blank=True, max_length=32)),
                ("owner_id", models.CharField(blank=True, max_length=64)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "ledger_account",
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=64)),
                ("minor_units", models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                "verbose_name_plural": "currencies",
                "db_table": "ledger_currency",
            },
        ),
        migrations.CreateModel(
            name="AccountBalance",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="balance",
                        serialize=False,
                        to="ledger.ledgeraccount",
                    ),
                ),
                ("balance", models.BigIntegerField(default=0)),
                ("version", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ledger_account_balance",
            },
        ),
        migrations.AddField(
            model_name="ledgeraccount",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to="ledger.currency",
            ),
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("narrative", models.CharField(max_length=255)),
                ("reference_type", models.CharField(blank=True, max_length=32)),
                ("reference_id", models.CharField(blank=True, max_length=64)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
            ],
            options={
                "db_table": "ledger_journal_entry",
                "indexes": [
                    models.Index(
                        fields=["reference_type", "reference_id"],
                        name="ledger_jour_referen_98e846_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Posting",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("amount", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postings",
                        to="ledger.ledgeraccount",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postings",
                        to="ledger.journalentry",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_posting",
            },
        ),
        migrations.AddIndex(
            model_name="ledgeraccount",
            index=models.Index(
                fields=["owner_type", "owner_id"], name="ledger_acco_owner_t_d59d88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="posting",
            index=models.Index(
                fields=["account", "created_at"], name="ledger_post_account_658090_idx"
            ),
        ),
    ]
