# Generated by Django 5.1.6 on 2026-10-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="request_id",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
