# Generated by Django 5.1.6 on 2026-10-07 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_pin_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token_generation",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="RevokedToken",
            fields=[
                (
                    "jti",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("token_type", models.CharField(max_length=8)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revoked_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_revoked_token",
            },
        ),
    ]
