# Generated by Django 5.1.6 on 2026-10-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_token_generation_revokedtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="anonymised_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="closed_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="pin_reset_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
