# Generated by Django 5.2.18 on 2026-10-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_user_anonymised_at_user_closed_at_user_closed_reason_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="gps_address",
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
