# Generated by Django 5.1.6 on 2026-10-07 13:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=16, unique=True)),
                ("destination_type", models.CharField(max_length=8)),
                ("institution", models.CharField(max_length=32)),
                ("account", models.CharField(max_length=34)),
                ("account_name", models.CharField(blank=True, max_length=128)),
                ("amount_minor", models.BigIntegerField()),
                ("currency", models.CharField(default="GHS", max_length=3)),
                ("narrative", models.CharField(blank=True, max_length=140)),
                ("connector", models.CharField(max_length=32)),
                (
                    "provider_ref",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed (refunded to wallet)"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("failure_code", models.CharField(blank=True, max_length=32)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wallet_external_transfer",
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="wallet_exte_status_c085a7_idx",
                    )
                ],
            },
        ),
    ]
