# Generated by Django 5.1.6 on 2026-10-07 14:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InboundRemittance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("partner", models.CharField(max_length=32)),
                ("partner_ref", models.CharField(max_length=64)),
                ("recipient_phone", models.CharField(max_length=16)),
                ("amount_minor", models.BigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("sender_name", models.CharField(blank=True, max_length=150)),
                ("sender_country", models.CharField(blank=True, max_length=2)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("credited", "Credited to wallet"),
                            ("rejected", "Rejected (partner returns it to the sender)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inbound_remittances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wallet_inbound_remittance",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("partner", "partner_ref"), name="uniq_remittance_ref"
                    )
                ],
            },
        ),
    ]
