# Generated by Django 5.1.6 on 2026-10-08 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_inboundremittance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="externaltransfer",
            index=models.Index(
                fields=["sender", "created_at"], name="wallet_exte_sender__fc96d8_idx"
            ),
        ),
    ]
