# Generated by Django 5.1.6 on 2026-10-08 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_walletnumber"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedRecipient",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("sokopay", "SokoPay user"),
                            ("momo", "Mobile money"),
                            ("bank", "Bank account"),
                            ("wallet", "Other wallet"),
                            ("merchant", "Merchant"),
                        ],
                        max_length=10,
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                ("value", models.CharField(max_length=34)),
                ("institution", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_recipients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wallet_saved_recipient",
                "indexes": [
                    models.Index(
                        fields=["owner", "kind"], name="wallet_save_owner_i_d64a23_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "kind", "value", "institution"),
                        name="uniq_saved_recipient",
                    )
                ],
            },
        ),
    ]
