# Generated by Django 5.1.6 on 2026-10-08 13:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0005_saved_recipients"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CrossBorderTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=16, unique=True)),
                ("provider", models.CharField(max_length=32)),
                ("quote_id", models.CharField(max_length=64)),
                ("country", models.CharField(max_length=2)),
                ("method", models.CharField(max_length=16)),
                ("account", models.CharField(max_length=34)),
                ("institution", models.CharField(max_length=32)),
                ("recipient_name", models.CharField(max_length=120)),
                ("purpose", models.CharField(max_length=32)),
                ("amount_minor", models.BigIntegerField()),
                ("fee_minor", models.BigIntegerField()),
                ("total_minor", models.BigIntegerField()),
                ("receive_amount", models.CharField(max_length=24)),
                ("receive_currency", models.CharField(max_length=3)),
                ("rate", models.CharField(max_length=24)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "On its way"),
                            ("succeeded", "Delivered"),
                            ("failed", "Failed, refunded"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "provider_ref",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cross_border_sends",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wallet_cross_border_transfer",
                "indexes": [
                    models.Index(
                        fields=["sender", "created_at"],
                        name="wallet_cros_sender__3760b8_idx",
                    ),
                    models.Index(
                        fields=["status", "updated_at"],
                        name="wallet_cros_status_49421c_idx",
                    ),
                ],
            },
        ),
    ]
