# Generated by Django 5.1.6 on 2026-10-08 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0006_cross_border"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LifestyleOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=16, unique=True)),
                ("category", models.CharField(max_length=12)),
                ("partner", models.CharField(max_length=48)),
                ("offering_code", models.CharField(max_length=64)),
                ("offering_name", models.CharField(max_length=150)),
                ("quantity", models.PositiveSmallIntegerField()),
                ("unit_price_minor", models.BigIntegerField()),
                ("total_minor", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Processing"),
                            ("succeeded", "Confirmed"),
                            ("failed", "Failed, refunded"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "provider_ref",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("token", models.CharField(blank=True, max_length=128)),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifestyle_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wallet_lifestyle_order",
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="wallet_life_user_id_688277_idx",
                    ),
                    models.Index(
                        fields=["status", "updated_at"],
                        name="wallet_life_status_3abbd8_idx",
                    ),
                ],
            },
        ),
    ]
