# Generated by Django 5.2.18 on 2026-10-08 22:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0006_paymentlink_checkoutsession"),
        ("portal", "0003_sms_device"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("login_locked", "Sign-in locked (too many wrong passwords)"),
                    ("twofa_enrolled", "2FA set up"),
                    ("twofa_locked", "2FA locked (too many wrong codes)"),
                    ("twofa_reset", "2FA reset by SokoPay staff"),
                    ("backup_used", "Backup code used to sign in"),
                    ("backup_regenerated", "Backup codes regenerated"),
                    ("invite_sent", "Portal invite sent"),
                    ("password_set", "Password set from an invite"),
                    ("password_reset", "Password reset with an SMS code"),
                    ("password_changed", "Password changed"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="PortalInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.CharField(blank=True, max_length=16)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="merchants.merchant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "portal_invite",
                "indexes": [
                    models.Index(
                        fields=["user", "used_at"],
                        name="portal_invi_user_id_3c613f_idx",
                    )
                ],
            },
        ),
    ]
