# Generated by Django 5.1.6 on 2026-10-07 13:56

import apps.common.encryption
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KycProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tier",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Basic (phone verified)"),
                            (1, "Verified (Ghana Card)"),
                            (2, "Enhanced (Ghana Card + selfie)"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "ghana_card_number",
                    apps.common.encryption.EncryptedCharField(blank=True),
                ),
                (
                    "ghana_card_hash",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("verified_name", models.CharField(blank=True, max_length=150)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("frozen", models.BooleanField(default=False)),
                ("frozen_reason", models.CharField(blank=True, max_length=255)),
                ("frozen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "frozen_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "KYC profile",
                "db_table": "kyc_profile",
            },
        ),
    ]
