# Generated by Django 5.1.6 on 2026-10-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycprofile",
            name="liveness_provider_ref",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="kycprofile",
            name="liveness_score",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="kycprofile",
            name="liveness_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="kycprofile",
            name="tier",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Minimum (phone verified)"),
                    (1, "Medium (Ghana Card verified)"),
                    (2, "Enhanced (Ghana Card + selfie)"),
                ],
                default=0,
            ),
        ),
    ]
