# Generated by Django 5.2.18 on 2026-10-09 12:06

import apps.common.encryption
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc", "0002_kycprofile_liveness_provider_ref_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentityDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("ghana_card", "Ghana Card"),
                            ("passport", "Passport"),
                            ("drivers_licence", "Driver's licence"),
                        ],
                        max_length=16,
                    ),
                ),
                ("number", apps.common.encryption.EncryptedCharField(blank=True)),
                ("number_last4", models.CharField(blank=True, max_length=4)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("front_key", models.CharField(max_length=256)),
                ("back_key", models.CharField(blank=True, max_length=256)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for review"),
                            ("verified", "Verified"),
                            ("rejected", "Not accepted"),
                            ("replaced", "Replaced by a newer upload"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("review_note", models.CharField(blank=True, max_length=255)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "kyc_identity_document",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="kyc_identit_status_63f14f_idx",
                    ),
                    models.Index(
                        fields=["user", "doc_type"],
                        name="kyc_identit_user_id_9d6da3_idx",
                    ),
                ],
            },
        ),
    ]
