# Generated by Django 5.1.6 on 2026-10-07 08:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReconRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rail", models.CharField(max_length=16)),
                ("date", models.DateField()),
                ("matched_count", models.IntegerField(default=0)),
                ("mismatch_count", models.IntegerField(default=0)),
                ("ours_only_count", models.IntegerField(default=0)),
                ("theirs_only_count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "recon_run",
                "indexes": [
                    models.Index(
                        fields=["rail", "date"], name="recon_run_rail_aeb3fe_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReconItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("mismatch", "Amount mismatch"),
                            ("ours_only", "In our records only"),
                            ("theirs_only", "In the rail's records only"),
                        ],
                        max_length=16,
                    ),
                ),
                ("rail_ref", models.CharField(max_length=64)),
                ("ours_minor", models.BigIntegerField(blank=True, null=True)),
                ("theirs_minor", models.BigIntegerField(blank=True, null=True)),
                ("resolved", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="reconciliation.reconrun",
                    ),
                ),
            ],
            options={
                "db_table": "recon_item",
                "indexes": [
                    models.Index(
                        fields=["run", "resolved"], name="recon_item_run_id_9aae43_idx"
                    )
                ],
            },
        ),
    ]
