# Generated by Django 5.1.6 on 2026-10-07 14:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SafeguardingCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("liabilities_minor", models.BigIntegerField()),
                ("trust_total_minor", models.BigIntegerField(blank=True, null=True)),
                ("surplus_minor", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Fully backed"),
                            ("shortfall", "SHORTFALL — e-money exceeds trust funds"),
                            ("stale", "Trust balance out of date"),
                            ("no_data", "No trust balance recorded"),
                        ],
                        max_length=10,
                    ),
                ),
                ("detail", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "safeguarding_check",
            },
        ),
        migrations.CreateModel(
            name="TrustAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bank_name", models.CharField(max_length=100)),
                ("account_name", models.CharField(max_length=150)),
                ("account_last4", models.CharField(max_length=4)),
                ("connector", models.CharField(blank=True, max_length=32)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "safeguarding_trust_account",
            },
        ),
        migrations.CreateModel(
            name="TrustBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("balance_minor", models.BigIntegerField()),
                ("as_of", models.DateTimeField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Entered from bank statement"),
                            ("api", "Bank balance API"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balances",
                        to="safeguarding.trustaccount",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "safeguarding_trust_balance",
                "indexes": [
                    models.Index(
                        fields=["account", "as_of"],
                        name="safeguardin_account_0f27be_idx",
                    )
                ],
            },
        ),
    ]
