# Generated by Django 5.1.6 on 2026-10-07 01:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Biller",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("electricity", "Electricity"),
                            ("water", "Water"),
                            ("tv", "TV"),
                            ("airtime", "Airtime"),
                            ("data", "Data"),
                            ("internet", "Internet"),
                            ("education", "Education"),
                        ],
                        max_length=16,
                    ),
                ),
                ("rail_biller_code", models.CharField(max_length=64)),
                ("network", models.CharField(blank=True, max_length=16)),
                ("supports_lookup", models.BooleanField(default=False)),
                ("min_minor", models.BigIntegerField(default=100)),
                ("max_minor", models.BigIntegerField(default=10000000)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "payments_biller",
                "ordering": ("category", "name"),
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=16, unique=True),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("bill", "Bill payment"),
                            ("airtime", "Airtime"),
                            ("data", "Data"),
                            ("merchant", "Merchant payment"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="created",
                        max_length=16,
                    ),
                ),
                ("account_ref", models.CharField(blank=True, max_length=64)),
                ("amount_minor", models.BigIntegerField()),
                ("fee_minor", models.BigIntegerField(default=0)),
                ("total_minor", models.BigIntegerField()),
                ("currency", models.CharField(default="GHS", max_length=3)),
                ("network", models.CharField(max_length=16)),
                ("payer", models.CharField(blank=True, max_length=32)),
                ("rail", models.CharField(max_length=16)),
                (
                    "rail_ref",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("failure_code", models.CharField(blank=True, max_length=32)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("live", "Live"), ("test", "Test")],
                        default="live",
                        max_length=4,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "biller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payments.biller",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payments_payment",
            },
        ),
        migrations.CreateModel(
            name="RailEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rail", models.CharField(max_length=16)),
                ("provider_ref", models.CharField(db_index=True, max_length=64)),
                ("status", models.CharField(max_length=16)),
                ("signature_ok", models.BooleanField()),
                ("payload", models.JSONField(default=dict)),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rail_events",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "db_table": "payments_rail_event",
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "created_at"], name="payments_pa_status_343680_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["purpose", "status"], name="payments_pa_purpose_8579eb_idx"
            ),
        ),
    ]
