# Generated by Django 5.1.6 on 2026-10-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_merchant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("bill", "Bill payment"),
                    ("airtime", "Airtime"),
                    ("data", "Data"),
                    ("merchant", "Merchant payment"),
                    ("wallet_fund", "Wallet funding"),
                ],
                max_length=16,
            ),
        ),
    ]
