# Generated by Django 5.1.6 on 2026-10-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="biller",
            name="connector",
            field=models.CharField(default="rail", max_length=32),
        ),
        migrations.AddField(
            model_name="payment",
            name="delivery_token",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="payment",
            name="product_code",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
