# Generated by Django 5.1.6 on 2026-10-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_biller_connector_payment_delivery_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="funding_source",
            field=models.CharField(
                choices=[
                    ("momo", "Mobile money (collected via the rail)"),
                    ("wallet", "SokoPay wallet (DEMI)"),
                ],
                default="momo",
                max_length=8,
            ),
        ),
    ]
