# Generated by Django 5.1.6 on 2026-10-08 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0003_settlement_failure_code_settlement_rail_and_more"),
        ("payments", "0006_payment_payments_pa_merchan_22280c_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["user", "created_at"], name="payments_pa_user_id_5bbfc5_idx"
            ),
        ),
    ]
