# Generated by Django 5.1.6 on 2026-10-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_payment_payments_pa_user_id_5bbfc5_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="source_ref",
            field=models.CharField(blank=True, max_length=48),
        ),
    ]
