# Generated by Django 5.1.6 on 2026-10-07 01:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("legal_name", models.CharField(max_length=200)),
                ("trading_name", models.CharField(blank=True, max_length=200)),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("registered", "Registered business"),
                            ("sole_trader", "Sole proprietor / individual"),
                        ],
                        max_length=16,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=64)),
                ("tin", models.CharField(blank=True, max_length=32)),
                ("registration_no", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("in_review", "In review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "risk_tier",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=8,
                    ),
                ),
                ("rejection_reason", models.CharField(blank=True, max_length=255)),
                ("mdr_bp", models.PositiveIntegerField(default=150)),
                ("mdr_cap_minor", models.BigIntegerField(default=5000)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_merchants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "merchants_merchant",
            },
        ),
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[("test", "Test"), ("live", "Live")], max_length=4
                    ),
                ),
                ("prefix", models.CharField(db_index=True, max_length=24, unique=True)),
                ("key_hash", models.CharField(max_length=64)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="merchants.merchant",
                    ),
                ),
            ],
            options={
                "db_table": "merchants_api_key",
            },
        ),
        migrations.CreateModel(
            name="MerchantDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("owner_id", "Owner Ghana Card"),
                            ("registration", "Business registration"),
                            ("tin", "TIN certificate"),
                            ("premises", "Photo of premises"),
                        ],
                        max_length=16,
                    ),
                ),
                ("storage_key", models.CharField(blank=True, max_length=256)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="uploaded",
                        max_length=8,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="merchants.merchant",
                    ),
                ),
            ],
            options={
                "db_table": "merchants_document",
            },
        ),
        migrations.CreateModel(
            name="MerchantMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("finance", "Finance"),
                            ("cashier", "Cashier"),
                            ("developer", "Developer"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="merchants.merchant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "merchants_member",
            },
        ),
        migrations.CreateModel(
            name="SettlementAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("momo", "Mobile money"), ("bank", "Bank account")],
                        max_length=8,
                    ),
                ),
                ("provider", models.CharField(max_length=32)),
                ("account_no", models.CharField(max_length=32)),
                ("account_name", models.CharField(max_length=128)),
                (
                    "name_check_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("matched", "Matched"),
                            ("mismatch", "Mismatch"),
                        ],
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement_accounts",
                        to="merchants.merchant",
                    ),
                ),
            ],
            options={
                "db_table": "merchants_settlement_account",
            },
        ),
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_minor", models.BigIntegerField()),
                ("currency", models.CharField(default="GHS", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_approval", "Awaiting approval"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rail_ref", models.CharField(blank=True, max_length=64)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="merchants.merchant",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="merchants.settlementaccount",
                    ),
                ),
            ],
            options={
                "db_table": "merchants_settlement",
            },
        ),
        migrations.AddIndex(
            model_name="merchant",
            index=models.Index(fields=["status"], name="merchants_m_status_128a55_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="merchantmember",
            unique_together={("merchant", "user")},
        ),
        migrations.AddIndex(
            model_name="settlement",
            index=models.Index(
                fields=["merchant", "status"], name="merchants_s_merchan_159f6f_idx"
            ),
        ),
    ]
