# Generated by Django 5.1.6 on 2026-10-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0002_merchant_short_code_paymentrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="settlement",
            name="failure_code",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="settlement",
            name="rail",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name="settlement",
            name="rail_ref",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
