# Generated by Django 5.1.6 on 2026-10-08 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0003_settlement_failure_code_settlement_rail_and_more"),
        ("payments", "0007_payment_payments_pa_user_id_5bbfc5_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("not_received", "I didn't get what I paid for"),
                            ("not_as_described", "Not as described / faulty"),
                            ("wrong_amount", "I was charged the wrong amount"),
                            ("duplicate", "I was charged twice"),
                            ("unauthorised", "I didn't make this payment"),
                            ("other", "Something else"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=1000)),
                ("amount_minor", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Waiting for the merchant"),
                            ("responded", "Merchant answered, SokoPay reviewing"),
                            ("resolved_customer", "Resolved, refunded"),
                            ("resolved_merchant", "Resolved in the merchant's favour"),
                            ("withdrawn", "Withdrawn by the customer"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("respond_by", models.DateTimeField()),
                ("merchant_response", models.CharField(blank=True, max_length=1000)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.CharField(blank=True, max_length=1000)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes",
                        to="merchants.merchant",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes",
                        to="payments.payment",
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "merchants_dispute",
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_minor", models.BigIntegerField()),
                ("currency", models.CharField(default="GHS", max_length=3)),
                ("reason", models.CharField(max_length=255)),
                (
                    "destination",
                    models.CharField(
                        choices=[
                            ("wallet", "SokoPay wallet"),
                            ("momo", "Mobile money"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("succeeded", "Refunded"),
                            ("failed", "Failed, money back in the merchant balance"),
                        ],
                        default="processing",
                        max_length=12,
                    ),
                ),
                ("rail", models.CharField(blank=True, max_length=16)),
                (
                    "rail_ref",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="merchants.dispute",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="merchants.merchant",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="payments.payment",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "merchants_refund",
            },
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["merchant", "status"], name="merchants_d_merchan_8adf85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["status", "respond_by"], name="merchants_d_status_b593e7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dispute",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("open", "responded"))),
                fields=("payment",),
                name="one_active_dispute_per_payment",
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(
                fields=["merchant", "created_at"], name="merchants_r_merchan_b99c03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(
                fields=["status", "updated_at"], name="merchants_r_status_fb6a4b_idx"
            ),
        ),
    ]
