# Generated by Django 5.1.6 on 2026-10-08 12:24

import apps.common.encryption
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0004_refunds_disputes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(max_length=300)),
                ("secret", apps.common.encryption.EncryptedCharField()),
                ("events", models.JSONField(default=list)),
                ("active", models.BooleanField(default=True)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("disabled_reason", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_endpoints",
                        to="merchants.merchant",
                    ),
                ),
            ],
            options={
                "db_table": "merchants_webhook_endpoint",
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_id", models.CharField(db_index=True, max_length=40)),
                ("event_type", models.CharField(max_length=32)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Delivered"),
                            ("failed", "Retrying"),
                            ("abandoned", "Gave up"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_status_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("last_error", models.CharField(blank=True, max_length=255)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="merchants.webhookendpoint",
                    ),
                ),
            ],
            options={
                "db_table": "merchants_webhook_delivery",
                "indexes": [
                    models.Index(
                        fields=["status", "next_attempt_at"],
                        name="merchants_w_status_0d7bc0_idx",
                    ),
                    models.Index(
                        fields=["endpoint", "created_at"],
                        name="merchants_w_endpoin_575ad4_idx",
                    ),
                ],
            },
        ),
    ]
