# Generated by Django 5.1.6 on 2026-10-08 13:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0005_webhooks"),
        ("payments", "0008_payment_source_ref"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(max_length=32, unique=True)),
                ("title", models.CharField(max_length=80)),
                ("description", models.CharField(blank=True, max_length=240)),
                ("amount_minor", models.BigIntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("max_uses", models.PositiveIntegerField(blank=True, null=True)),
                ("uses", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_links",
                        to="merchants.merchant",
                    ),
                ),
            ],
            options={
                "db_table": "merchants_payment_link",
            },
        ),
        migrations.CreateModel(
            name="CheckoutSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(max_length=32, unique=True)),
                ("amount_minor", models.BigIntegerField()),
                ("description", models.CharField(blank=True, max_length=120)),
                ("merchant_reference", models.CharField(blank=True, max_length=64)),
                ("success_url", models.URLField(blank=True, max_length=300)),
                ("cancel_url", models.URLField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Awaiting payment"),
                            ("paid", "Paid"),
                            ("expired", "Expired"),
                        ],
                        default="open",
                        max_length=8,
                    ),
                ),
                ("mode", models.CharField(default="live", max_length=4)),
                ("expires_at", models.DateTimeField()),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkout_sessions",
                        to="merchants.merchant",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "db_table": "merchants_checkout_session",
                "indexes": [
                    models.Index(
                        fields=["merchant", "merchant_reference"],
                        name="merchants_c_merchan_c0b7da_idx",
                    )
                ],
            },
        ),
    ]
