# Generated by Django 5.1.6 on 2026-10-08 10:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchlistEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("un", "UN Security Council consolidated list"),
                            ("ofac", "US OFAC SDN"),
                            ("eu", "EU consolidated list"),
                            ("gh", "Ghana domestic list"),
                            ("pep", "Politically exposed persons"),
                            ("custom", "Internal / custom"),
                        ],
                        db_index=True,
                        max_length=8,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("sanctions", "Sanctions"),
                            ("pep", "Politically exposed person"),
                        ],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("normalised", models.JSONField(blank=True, default=list)),
                ("dob", models.CharField(blank=True, max_length=32)),
                ("nationality", models.CharField(blank=True, max_length=64)),
                ("reference", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "compliance_watchlist_entry",
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rule", models.CharField(db_index=True, max_length=40)),
                ("title", models.CharField(max_length=160)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigating", "Investigating"),
                            ("escalated", "Escalated"),
                            ("closed_no_action", "Closed — no further action"),
                            ("closed_reported", "Closed — reported to FIC"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "subject_kind",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("agent", "Agent"),
                            ("merchant", "Merchant"),
                        ],
                        max_length=10,
                    ),
                ),
                ("subject_id", models.CharField(max_length=64)),
                ("subject_label", models.CharField(max_length=160)),
                ("hits", models.PositiveIntegerField(default=1)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now_add=True)),
                ("evidence", models.JSONField(blank=True, default=list)),
                ("closed_reason", models.CharField(blank=True, max_length=255)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aml_alerts_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aml_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "compliance_alert",
            },
        ),
        migrations.CreateModel(
            name="AlertNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("note", "Note"),
                            ("status", "Status change"),
                            ("hold", "Hold placed"),
                            ("release", "Hold released"),
                            ("assign", "Assigned"),
                            ("system", "System"),
                        ],
                        default="note",
                        max_length=8,
                    ),
                ),
                ("text", models.TextField(max_length=4000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="compliance.alert",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "compliance_alert_note",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="LargeTransactionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_id", models.CharField(max_length=64, unique=True)),
                ("kind", models.CharField(max_length=32)),
                ("direction", models.CharField(max_length=3)),
                ("amount_minor", models.BigIntegerField()),
                ("occurred_at", models.DateTimeField()),
                ("exported_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "compliance_large_txn_report",
            },
        ),
        migrations.CreateModel(
            name="SuspiciousTransactionReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject_label", models.CharField(max_length=160)),
                ("narrative", models.TextField(max_length=10000)),
                ("transactions", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved — ready to file"),
                            ("filed", "Filed with FIC"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("filed_at", models.DateTimeField(blank=True, null=True)),
                ("fic_reference", models.CharField(blank=True, max_length=64)),
                (
                    "alerts",
                    models.ManyToManyField(
                        related_name="reports", to="compliance.alert"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "compliance_str",
            },
        ),
        migrations.CreateModel(
            name="ScreeningMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entry_name", models.CharField(max_length=255)),
                ("entry_kind", models.CharField(max_length=10)),
                ("name_screened", models.CharField(max_length=255)),
                ("score", models.DecimalField(decimal_places=3, max_digits=4)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("confirmed", "Confirmed match"),
                            ("cleared", "Cleared — not the same person"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="compliance.alert",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="screening_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches",
                        to="compliance.watchlistentry",
                    ),
                ),
            ],
            options={
                "db_table": "compliance_screening_match",
            },
        ),
        migrations.CreateModel(
            name="WatchlistImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("un", "UN Security Council consolidated list"),
                            ("ofac", "US OFAC SDN"),
                            ("eu", "EU consolidated list"),
                            ("gh", "Ghana domestic list"),
                            ("pep", "Politically exposed persons"),
                            ("custom", "Internal / custom"),
                        ],
                        max_length=8,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("entries", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "compliance_watchlist_import",
            },
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["status", "severity", "created_at"],
                name="compliance__status_a0be38_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["subject_kind", "subject_id", "rule", "status"],
                name="compliance__subject_3b793f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="largetransactionreport",
            index=models.Index(
                fields=["exported_at", "occurred_at"],
                name="compliance__exporte_6b5ac4_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="screeningmatch",
            constraint=models.UniqueConstraint(
                fields=("user", "entry"), name="uniq_user_watchlist_entry"
            ),
        ),
    ]
