# Generated by Django 5.1.6 on 2026-10-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="largetransactionreport",
            name="entry_id",
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
